# Generated by Django 4.0.4 on 2022-08-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litreview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='user_id',
        ),
    ]
