# Generated by Django 4.1 on 2022-09-19 16:43

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('litreview', '0006_alter_review_options_alter_review_body_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_email'),
        ),
    ]
